# Generated by Django 2.2 on 2019-04-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='url',
            new_name='urla',
        ),
    ]
