# Generated by Django 2.2 on 2019-05-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190425_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='urla',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
